/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package weddingapplicationlogin;

import java.awt.Button;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static weddingapplicationlogin.UserRequest.jTable1;
import static weddingapplicationlogin.UserRequest.jTextField1;

/**
 *
 * @author shwez
 */
public class User_details extends javax.swing.JFrame {
   
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    private Object JtextField1;
    private Button button;
    
    /**
     * Creates new form AdminPage
     */
    public  User_details(){
        initComponents();
          
        try{
            
            con = WeddingApplicationLogin.getConnection();
            pst = con.prepareStatement("SELECT  `username`, `email`, `dob`, `address`, `mobile`, `status` FROM `login_table` WHERE options = \"User\" ");
            rs= pst.executeQuery();
           
            Vector total_row = new Vector();
            Vector column_heading = new Vector();
            
            column_heading.addElement("Username");
            column_heading.addElement("Email");
            column_heading.addElement("DOB");
            column_heading.addElement("Address");
            column_heading.addElement("Contact");
            column_heading.addElement("Status");
           
            while(rs.next()){
                Vector newRecord = new Vector();
                newRecord.addElement(rs.getString("username"));
                newRecord.addElement(rs.getString("email"));
                newRecord.addElement(rs.getString("dob"));
                newRecord.addElement(rs.getString("address"));
                newRecord.addElement(rs.getString("mobile"));
                newRecord.addElement(rs.getString("status"));
                
                total_row.addElement(newRecord);
           }
            DefaultTableModel model = new DefaultTableModel(total_row,column_heading);
            jTable1.setModel(model);
            
                  
        }catch(Exception e){
            System.out.println(""+e);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("HOME");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 70, 60));

        jButton3.setBackground(new java.awt.Color(153, 204, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("ADD PLANNER");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 140, 60));

        jButton4.setBackground(new java.awt.Color(153, 204, 255));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setText("USER REQUEST");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 130, 60));

        jLabel4.setBackground(new java.awt.Color(153, 204, 255));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("USER DETAILS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 140, 60));

        jButton7.setBackground(new java.awt.Color(153, 204, 255));
        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton7.setText("LOGOUT");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, 120, 60));

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 3, 24)); // NOI18N
        jLabel3.setText("Wedding Planner Management System ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 60));

        jScrollPane1.setBackground(new java.awt.Color(153, 153, 255));
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Firstname", "Lastname", "Username", "Email", "DOB", "Address","Contact"
            }

        )
        {
            public boolean isCellEditable(int row,int column){
                return false;
            }
        }
    );
    jTable1.getTableHeader().setReorderingAllowed(false);
    jTable1.addAncestorListener(new javax.swing.event.AncestorListener() {
        public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
        }
        public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            jTable1AncestorAdded(evt);
        }
        public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
        }
    });
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable1MouseClicked(evt);
        }
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            jTable1MouseEntered(evt);
        }
    });
    jScrollPane1.setViewportView(jTable1);

    getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 690, 110));

    jLabel2.setFont(new java.awt.Font("Liberation Serif", 1, 24)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(69, 185, 185));
    jLabel2.setText("USER DETAILS");
    jLabel2.setBorder(new javax.swing.border.MatteBorder(null));
    getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, 180, 60));

    jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
    jLabel5.setText("(Add Username to update the status)");
    getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 390, -1, -1));

    jTextField1.setEditable(false);
    jTextField1.setBackground(new java.awt.Color(204, 255, 255));
    jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
    jTextField1.setToolTipText("Enter Username");
    jTextField1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField1ActionPerformed(evt);
        }
    });
    getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 160, 40));

    jButton2.setBackground(new java.awt.Color(151, 151, 242));
    jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
    jButton2.setText("DE-ACTIVATE");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });
    getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 430, -1, 40));

    jButton6.setBackground(new java.awt.Color(151, 151, 242));
    jButton6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
    jButton6.setText("ACTIVATE");
    jButton6.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton6ActionPerformed(evt);
        }
    });
    getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, -1, 40));

    jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\shwez\\Desktop\\bg.jpg")); // NOI18N
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 610));

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        AddPlanner ap = new AddPlanner();
        ap.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        UserRequest ur = new UserRequest();
        ur.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AdminPage ap = new AdminPage();
        ap.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

  
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
   String status = jTextField1.getText();
                 
        if(status.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Enter Username to update..!", "Error",1);
        }else{
            try{
               
                    con = WeddingApplicationLogin.getConnection();
                    pst = con.prepareStatement("UPDATE `login_table` SET `status`=\"INACTIVE\" WHERE options=\"User\" AND username= ? ");
                    pst.setString(1,status);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(rootPane, "Updated Successfully!");
                 
                    DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
                    model.setRowCount(0);
                    show_User();
                    
                   AdminPage ap = new AdminPage();
                   ap.setVisible(true);
                   this.setVisible(false);
                 
            }catch(Exception e){
                System.out.println(""+e);
            }
        }     
    }//GEN-LAST:event_jButton2ActionPerformed
     
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String status = jTextField1.getText();
                   
        if(status.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Enter Username to update..!", "Error",1);
        }else{
            try{
                con = WeddingApplicationLogin.getConnection();
                pst = con.prepareStatement("UPDATE `login_table` SET `status`=\"ACTIVE\" WHERE options=\"User\" AND username= ? ");
                pst.setString(1, status);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Updated Successfully!");           
              
                DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
                    model.setRowCount(0);
                    show_User();
                   
                AdminPage ap = new AdminPage();
                ap.setVisible(true);
                this.setVisible(false);
                
                }
                
                catch(Exception e){
                    System.out.println(""+e);
                }
            }
       
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTable1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable1AncestorAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTable1AncestorAdded

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jTable1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseEntered
        // TODO add your handling code here:
          try{
            
            con = WeddingApplicationLogin.getConnection();
            pst = con.prepareStatement("SELECT  `username`, `email`, `dob`, `address`, `mobile`, `status` FROM `login_table` WHERE options = \"User\" ");
            rs= pst.executeQuery();
           
            Vector total_row = new Vector();
            Vector column_heading = new Vector();
            
            column_heading.addElement("Username");
            column_heading.addElement("Email");
            column_heading.addElement("DOB");
            column_heading.addElement("Address");
            column_heading.addElement("Contact");
            column_heading.addElement("Status");
            
            while(rs.next()){
                Vector newRecord = new Vector();
                newRecord.addElement(rs.getString("username"));
                newRecord.addElement(rs.getString("email"));
                newRecord.addElement(rs.getString("dob"));
                newRecord.addElement(rs.getString("address"));
                newRecord.addElement(rs.getString("mobile"));
                newRecord.addElement(rs.getString("status"));
                
                total_row.addElement(newRecord);
           }
            DefaultTableModel model = new DefaultTableModel(total_row,column_heading);
            jTable1.setModel(model);
            
                  
        }catch(Exception e){
            System.out.println(""+e);
        }
        
    }//GEN-LAST:event_jTable1MouseEntered

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel tmodel = (DefaultTableModel)jTable1.getModel();
        int selectrowindex = jTable1.getSelectedRow();
        jTextField1.setText(tmodel.getValueAt(selectrowindex, 0).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_details().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void show_User() {
     
        try{
           
            Vector total_row = new Vector();
            Vector column_heading = new Vector();
            
            column_heading.addElement("Username");
            column_heading.addElement("Email");
            column_heading.addElement("DOB");
            column_heading.addElement("Address");
            column_heading.addElement("Contact");
            column_heading.addElement("Status");
            
            while(rs.next()){
                Vector newRecord = new Vector();
                newRecord.addElement(rs.getString("username"));
                newRecord.addElement(rs.getString("email"));
                newRecord.addElement(rs.getString("dob"));
                newRecord.addElement(rs.getString("address"));
                newRecord.addElement(rs.getString("mobile"));
                newRecord.addElement(rs.getString("status"));
                
                total_row.addElement(newRecord);
           }
            DefaultTableModel model = new DefaultTableModel(total_row,column_heading);
            jTable1.setModel(model);
            
                  
        }catch(Exception e){
            System.out.println(""+e);
        }
        
    }

    
}


